# Install command-line tools using Homebrew
# Usage: `brew bundle Brewfile`

# Make sure we're using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install GNU core utilities (those that come with OS X are outdated)
# Don't forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew install coreutils
# Install some other useful utilities like `sponge`
brew install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
brew install findutils
# Install GNU `sed`, overwriting the built-in `sed`
brew install gnu-sed --default-names
# Install Bash 4
# Note: don't forget to add `/usr/local/bin/bash` to `/etc/shells` before running `chsh`.
brew install bash
brew install bash-completion

# Install wget with IRI support
brew install wget --enable-iri

# Install more recent versions of some OS X tools
brew install vim --override-system-vi
brew install homebrew/dupes/grep
brew install homebrew/dupes/screen
# install homebrew/php/php55 --with-gmp

# Install other useful binaries
brew install ack
brew install cmake
brew install diff-so-fancy
brew install foremost
brew install git
brew install bash-completion
brew install hub
brew install gifsicle
brew install imagemagick --with-webp
brew install lynx
brew install mercurial
brew install nmap
brew install node # This installs `npm` too using the recommended installation method
brew install ruby
brew install ruby-build
brew install spark
brew install tmux
brew install tree
brew install ucspi-tcp # `tcpserver` et al.
brew install xctool
brew install noti

# Remove outdated versions from the cellar
brew cleanup
