#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

. "$DOTFILES_ROOT/script/output.sh"

# find the installers and run them
while read -r installer
do
    topic=$(basename "$(dirname "$installer")")
    info "installing $topic"
    bash -c "$installer"
    success "installed $topic"
done < <(find . -name 'install*.sh' -maxdepth 2 | rev | sort | rev)
