#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# find the installers and run them
find . -name 'install*.sh' -maxdepth 2 | rev | sort | rev | while read installer ; do bash -c "$installer" ; done
